twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locales: '%app.locales%'
        PourcentageDeTouteLesInterventions: 0

when@test:
    twig:
        strict_variables: true
